### PR TITLE
Fix non-fest uber drop score

### PR DESCRIPTION
**Pull request by ricobonfim**
I believe that uber rarity should have precedence over uber_fest whenever possible, because it would always drop an uber. Currently, any score between 9470...9500 is considered uber_fest, which might lead someone to wait for a *fest event just to get a uber that he would get anyway.

Example
uber_fest_rarity_on_always_uber

### CODE REVIEW

**Comment by godfat** [comment]
Would you like to move to https://gitlab.com/godfat/battle-cats-rolls
? I am not really maintaining it here.

**Comment by ricobonfim** [comment]
Sure, thanks for all the hard work on this ;)

**Comment by godfat** [comment]
You're welcome, and thanks for offering help. There's a reason that
it's done this way, and back then there's no legendary cats but then
legendary cats started to make this confusing. I need to think this
through and I would get back on this later. (on the new merge request
if you can, thanks!)

**Comment by ricobonfim** [comment]
https://gitlab.com/godfat/battle-cats-rolls/-/merge_requests/9

Done! Let's keep the discussion there then... Closing this PR

**Pull request closed without merging**
